version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - ls
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://$DEPLOY_BUCKET_NAME --delete
artifacts:
  base-directory: build
  files:
    - "**/*"