trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Set by Terraform
  - name: BACKEND_URL
    value: $(BACKEND_URL)
  - name: SENTRY_AUTH_TOKEN
    value: $(SENTRY_AUTH_TOKEN)
  - name: ENVIRONMENT
    value: $(ENVIRONMENT)
  - name: STORAGE_ACCOUNT_NAME
    value: $(STORAGE_ACCOUNT_NAME)
  - name: RESOURCE_GROUP_NAME
    value: $(RESOURCE_GROUP_NAME)
  - name: FRONTDOOR_PROFILE_NAME
    value: $(FRONTDOOR_PROFILE_NAME)
  - name: FRONTDOOR_ENDPOINT_NAME
    value: $(FRONTDOOR_ENDPOINT_NAME)

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: npm install
            displayName: 'Install dependencies'

          - script: |
              export REACT_APP_BACKEND_URL=$(BACKEND_URL)
              export REACT_APP_SENTRY_AUTH_TOKEN=$(SENTRY_AUTH_TOKEN)
              export REACT_APP_ENVIRONMENT=$(ENVIRONMENT)
              npm run build
            displayName: 'Build application'

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: 'build'
              artifactName: 'build-output'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: $(ENVIRONMENT)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'build-output'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'Azure Service Connection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az storage blob service-properties update \
                        --account-name $(STORAGE_ACCOUNT_NAME) \
                        --static-website \
                        --404-document index.html \
                        --index-document index.html

                      az storage blob upload-batch \
                        --account-name $(STORAGE_ACCOUNT_NAME) \
                        --destination '$web' \
                        --source '$(System.ArtifactsDirectory)/build-output' \
                        --overwrite true

                      az cdn endpoint purge \
                        --resource-group $(RESOURCE_GROUP_NAME) \
                        --name $(FRONTDOOR_ENDPOINT_NAME) \
                        --profile-name $(FRONTDOOR_PROFILE_NAME) \
                        --content-paths "/*"
            displayName: 'Deploy to Azure and Purge CDN'

  - stage: Test
    displayName: 'Test Stage'
    dependsOn: Deploy
    jobs:
      - job: Test
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Azure Service Connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                CDN_URL=$(az cdn endpoint show \
                  --resource-group $(RESOURCE_GROUP_NAME) \
                  --name $(FRONTDOOR_ENDPOINT_NAME) \
                  --profile-name $(FRONTDOOR_PROFILE_NAME) \
                  --query "hostName" -o tsv)

                echo "Testing website at: https://$CDN_URL"
                curl -f "https://$CDN_URL" || exit 1

                echo "Website deployment successful!"
            displayName: 'Verify CDN URL'
